Search events with Form & Loader
bandungdevcom/bandungdev.com pull request #14
Opened 2023-11-02 10:46 UTC by agus-wesly

Using Form with default get method to trigger loader. Fetch filtered events and display it. I try to use the installed react-icons library to get search icon, but it throws error. So i use svg for temporary search icon.

2023-11-02 10:57 UTC, mhaidarhanif commented
@agus-wesly Use Iconify React to handle the icon

It's already setup like in the social media Icons in the footer

2023-11-03 07:17 UTC, mhaidarhanif requested changes
No need for useState, rely on the browser URL state when searching and filtering

When the search form submit with GET method, there will be URL search params

Use it to manage the search keyword state

2023-11-03 07:48 UTC, agus-wesly commented
> No need for useState, rely on the browser URL state when searching and filtering
> 
> When the search form submit with GET method, there will be URL search params that can be handled in the loader
> 
> Use it to manage the search keyword state

I already remove useState and do exactly this. Am i missing something ?

2023-11-03 07:53 UTC, mhaidarhanif requested changes
I see, the useState already removed

Then need to remove the stateful related code in other parts

2023-11-03 07:53 UTC, mhaidarhanif commented on app/components/ui/search-input.tsx
> +	setValue?: React.ChangeEventHandler<HTMLInputElement>
I meant this part is not needed

2023-11-03 07:53 UTC, mhaidarhanif commented on app/components/ui/search-input.tsx
> +				onChange={setValue}
This part also not needed

2023-11-03 07:55 UTC, mhaidarhanif commented
Also, use a more common query `q` to handle the search keyword

Because after the search, there will be a time to combine it with the pagination queries

2023-11-04 07:32 UTC, mhaidarhanif approved these changes
Looks okay for now. Although later need to improve the searching state or remove it because there's a jank when transitioning.

2023-11-04 07:33 UTC, merged