Event Location
bandungdevcom/bandungdev.com pull request #23
Opened 2023-12-24 07:40 UTC by fikrialwan

## What kind of change does this PR introduce?

Create function and UI to add event location when create event
- [x] create schema and seed data location categories
- [ ] create UI add event location
- [ ] create function to add event location
- [ ] show event location on event page detail 

## What is the current behavior?

- https://staging.bandungdev.com/events/2023-11-11
<img width="1440" alt="Screen Shot 2023-12-24 at 14 34 10" src="https://github.com/bandungdevcom/bandungdev.com/assets/26239542/6a7310a4-c5c4-48c4-91ee-06902859adc9">
&nbsp;

-  https://staging.bandungdev.com/admin/events/clqj6drub0006nz0pgbk4g0jc
<img width="1440" alt="Screen Shot 2023-12-24 at 14 36 59" src="https://github.com/bandungdevcom/bandungdev.com/assets/26239542/af31e764-59f3-4833-ae6c-0a0a8f69bc8f">
&nbsp;

&nbsp;
&nbsp;
Closes #5

2023-12-24 17:19 UTC, mhaidarhanif commented on prisma/data/location-categories.json
Can change Offline to In Person (IN_PERSON), like with Luma

2023-12-24 17:19 UTC, mhaidarhanif commented on prisma/schema.prisma
`link` here can be just `url`

Link would imply there are both `url`, `name`, `icon`, etc inside it.

2023-12-25 01:20 UTC, fikrialwan commented on prisma/data/location-categories.json
I've change Offline to In Person on this commit https://github.com/bandungdevcom/bandungdev.com/pull/23/commits/62c4fe5878e65f6045a3eadd49c7f1e41bb540d9 and format code with Prettier on this commit https://github.com/bandungdevcom/bandungdev.com/pull/23/commits/6ed31a587af32506a1c1f961da408ebf2af8920a

2023-12-25 01:22 UTC, fikrialwan commented on prisma/schema.prisma
i've changed link to be url on location schema on this commit https://github.com/bandungdevcom/bandungdev.com/pull/23/commits/21c191bb9eb81cb4e71644e1f8e54cc97441c3ad

2023-12-25 18:01 UTC, mhaidarhanif commented
@fikrialwan and @babdurrahman78 can use the same existing branch to work together, no need to create a separated branch.

2023-12-28 23:27 UTC, mhaidarhanif commented
@fikrialwan @babdurrahman78 Once it's ready, let me know so we can review it. Also possible to review together in the usual video call again.

2023-12-29 23:55 UTC, fikrialwan commented
@mhaidarhanif this pull request is ready now, for review together, I possible tonight

2023-12-30 11:40 UTC, mhaidarhanif requested changes
@fikrialwan @babdurrahman78 

- Fix import to use `~` such as `~/components`
- Remove organizerId requirement in model admin event
- Fix layout to edit the detail to be simpler in the middle
- Event Category radio button background color
- Event page to move Category to below Format, with just a text
- Rename Location (Offline) to Location (In Person)
- Show Maps URL below Location In Person

2023-12-30 13:59 UTC, fikrialwan commented
@mhaidarhanif 
I've done fix all of the feedback
- Fix import to use ~ such as ~/components https://github.com/bandungdevcom/bandungdev.com/pull/23/commits/41dd8e9201cb0d34366b88de72bf72aac77685c6
- Remove organizerId requirement in model admin event https://github.com/bandungdevcom/bandungdev.com/pull/23/commits/9af66ed61a836b96272b73077aa31ba5deeff797
- Fix layout to edit the detail to be simpler in the middle https://github.com/bandungdevcom/bandungdev.com/pull/23/commits/81f6ef857bd3e204560a111eb509fa57e96841de
- Event Category radio button background color  https://github.com/bandungdevcom/bandungdev.com/pull/23/commits/32d9773fa358465903a0e5acb6e6ccd897c7fa6f
- Event page to move Category to below Format, with just a text https://github.com/bandungdevcom/bandungdev.com/pull/23/commits/96586435aca1eab6504f2f2aea1d5fdb6f15e2a1
- Rename Location (Offline) to Location (In Person) https://github.com/bandungdevcom/bandungdev.com/pull/23/commits/c54ee41c973a4ddf398454e7688d4f2cc69091bc
- Show Maps URL below Location In Person https://github.com/bandungdevcom/bandungdev.com/pull/23/commits/35aea5d1c8e25c5f559451e9228b56ed43c90e22
- Fix render if location is null https://github.com/bandungdevcom/bandungdev.com/pull/23/commits/ae004ebe3edec0d3abaf68ffd76de3ae74c17990
- Don't show Format and Category label if the data is unavailable https://github.com/bandungdevcom/bandungdev.com/pull/23/commits/04dd87c8da6bab20dcf41fbe88c516b015376e49

2023-12-30 15:41 UTC, mhaidarhanif approved these changes

2023-12-30 15:42 UTC, merged